### ISSUE TITLE
Input: full-length or mature proteins

### ISSUE THREAD

**Issue by skyungyong** [mjnur/oomycete-effector-prediction#2]
Hello!

Thank you for developing the software! Is the tool designed to work the best with full-length sequences? Or would the mature sequences be better?

Thank you!
Kyungyong

**Comment by mjnur** [comment]
Hey there Kyungyong!

The model was trained/evaluated using the full length sequences (all with a predicted signal peptide), and the feature generation creates average amino acid stats based on the N-terminus of the sequence. Because of this I believe full-length sequences would work best but it'd be interesting to try mature sequences! 

A model based on mature sequences instead that only considers cleaved sequences might be something to look at, maybe this might reduce any noise coming from the signal peptide region.

Munir
